### ISSUE TITLE
Can someone help with Circle drawing program?

### ISSUE THREAD

**Issue by poudel-sandeep** [poudel-sandeep/HacktoberFest-2022#7]
A program can be in C or in Java. Thank you

**Comment by 1-Sandeep** [comment]
I can help you, as I have just completed my exam I can write some code

**Comment by poudel-sandeep** [comment]
yes you can, i will assign  you

**Comment by poudel-sandeep** [comment]
While doing with Bresenham make PR with circle_draw_algo_bresenham.fileextension_name
